# Generated by Django 4.2.16 on 2024-09-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["service_name"],
                "permissions": [
                    ("can_add_service", "Может добавлять услугу"),
                    ("can_change_service", "Может изменять услугу"),
                    ("can_view_service", "Может просматривать услугу"),
                ],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.RenameField(
            model_name="service",
            old_name="name",
            new_name="service_name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="picture",
        ),
    ]
