# Generated by Django 4.2.16 on 2024-09-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sitemap",
        ),
    ]
