# Generated by Django 4.2.16 on 2024-09-08 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ФИО врача")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=255, verbose_name="Специализация"),
                ),
                (
                    "qualification",
                    models.CharField(max_length=255, verbose_name="Квалификация"),
                ),
                ("experience", models.PositiveIntegerField(verbose_name="Стаж")),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="doctor/"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополинительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "врач",
                "verbose_name_plural": "врачи",
                "ordering": ["name", "specialization"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "пациент",
                "verbose_name_plural": "пациенты",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата исследования"
                    ),
                ),
                (
                    "medical_test",
                    models.CharField(
                        max_length=200, verbose_name="Название исследования"
                    ),
                ),
                (
                    "test_result",
                    models.CharField(max_length=150, verbose_name="Результат"),
                ),
                (
                    "units_of_measurement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Единицы измерения",
                    ),
                ),
                (
                    "reference_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Референсное значение",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
                "ordering": ["-date"],
                "permissions": [
                    ("can_view_results", "Может просматривать результаты исследования")
                ],
            },
        ),
        migrations.CreateModel(
            name="Appoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                ("record_time", models.TimeField(verbose_name="Время записи")),
                (
                    "doctor",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "permissions": [
                    ("can_add_record", "Может добавлять запись"),
                    ("can_change_record", "Может изменять запись"),
                    ("can_view_record", "Может просматривать запись"),
                    ("can_delete_record", "Может удалять запись"),
                ],
            },
        ),
    ]
