# Generated by Django 4.2.16 on 2024-09-23 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ФИО врача")),
                (
                    "specialization",
                    models.CharField(max_length=500, verbose_name="Специализация"),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Квалификация",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стаж"
                    ),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="doctor/"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["name", "specialization"],
                "permissions": [
                    ("can_edit_name", "Can Edit Doctor Name"),
                    ("can_edit_specialization", "Can Edit Specialization"),
                    ("can_edit_avatar", "Can Edit Doctor Avatar"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="patient/"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "ordering": ["last_name"],
                "permissions": [
                    ("can_edit_email", "Can Edit Patient eMail"),
                    ("can_edit_photo", "Can Edit Patient Photo"),
                    ("can_edit_birthday", "Can Edit Patient Birthday"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата исследования"
                    ),
                ),
                (
                    "medical_test",
                    models.CharField(
                        max_length=200, verbose_name="Название исследования"
                    ),
                ),
                (
                    "test_result",
                    models.CharField(max_length=150, verbose_name="Результат"),
                ),
                (
                    "units_of_measurement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Единицы измерения",
                    ),
                ),
                (
                    "reference_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Референсное значение",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
                "ordering": ["-date"],
                "permissions": [
                    ("can_edit_test_name", "Can Edit Result Name"),
                    ("can_edit_test_date", "Can Edit Result Date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Appoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appoint_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата приема врача"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="main.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="main.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-appoint_date"],
            },
        ),
    ]
