# Generated by Django 4.2.16 on 2024-09-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appoint",
            options={
                "permissions": [
                    ("сan_add_appoint", "Can Add Appoint"),
                    ("can_change_appoint", "Can Edit Appoint"),
                    ("can_delete_appoint", "Can Delete Appoint"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["name", "specialization"],
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.AlterModelOptions(
            name="result",
            options={
                "ordering": ["-date"],
                "permissions": [("can_view_results", "Can View Results")],
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
            },
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="age",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарии"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(max_length=500, verbose_name="Квалификация"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(max_length=500, verbose_name="Специализация"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="owner",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
