# Generated by Django 4.2.16 on 2024-09-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_patient_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appoint",
            options={
                "ordering": ["-record_date", "record_time"],
                "permissions": [
                    ("сan_add_appoint", "Can Add Appoint"),
                    ("can_change_appoint", "Can Edit Appoint"),
                    ("can_delete_appoint", "Can Delete Appoint"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.RemoveField(
            model_name="patient",
            name="surname",
        ),
        migrations.AlterField(
            model_name="appoint",
            name="doctor",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="main.doctor",
                verbose_name="Врач",
            ),
        ),
        migrations.AlterField(
            model_name="appoint",
            name="owner",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
        migrations.AlterField(
            model_name="appoint",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="main.patient",
                verbose_name="Пациент",
            ),
        ),
    ]
