# Generated by Django 4.2.16 on 2024-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_appoint_options_remove_patient_surname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
    ]
