# Generated by Django 4.2.16 on 2024-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_patient_surname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appoint",
            options={
                "ordering": ["-appoint_date"],
                "permissions": [
                    ("сan_add_appoint", "Can Add Appoint"),
                    ("can_change_appoint", "Can Edit Appoint"),
                    ("can_delete_appoint", "Can Delete Appoint"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.RemoveField(
            model_name="appoint",
            name="record_date",
        ),
        migrations.RemoveField(
            model_name="appoint",
            name="record_time",
        ),
        migrations.AddField(
            model_name="appoint",
            name="appoint_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата приема врача"
            ),
        ),
    ]
