# Generated by Django 4.2.16 on 2024-09-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_appoint_options_remove_appoint_record_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["name", "specialization"],
                "permissions": [
                    ("can_edit_name", "Can Edit Doctor Name"),
                    ("can_edit_specialization", "Can Edit Specialization"),
                    ("can_edit_avatar", "Can Edit Doctor Avatar"),
                ],
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["last_name"],
                "permissions": [
                    ("can_edit_email", "Can Edit Patient eMail"),
                    ("can_edit_photo", "Can Edit Patient Photo"),
                    ("can_edit_birthday", "Can Edit Patient Birthday"),
                ],
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.AlterModelOptions(
            name="result",
            options={
                "ordering": ["-date"],
                "permissions": [("can_edit_test_result", "Can Edit Results")],
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
            },
        ),
    ]
