# Generated by Django 4.2.16 on 2024-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_appoint_options_alter_result_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стаж"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Квалификация"
            ),
        ),
    ]
