# Generated by Django 4.2.16 on 2024-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_doctor_experience_alter_doctor_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
